#---------------------------------------
#  Virtual machine settings
#---------------------------------------

vm:
    memory: 256
    gui: false
    ip: 10.0.1.100 # or dhcp

#---------------------------------------
#  System preferences
#---------------------------------------

timezone: "Europe/Budapest"

locales:
    - en_US.UTF-8 UTF-8
    - hu_HU.UTF-8 UTF-8

#---------------------------------------
#  Services
#---------------------------------------

# php:
#     version: 5.5 # or 5.4 or 5.3
#     modules:
#         - curl
#         - gd
#         - gearman
#         - imagick
#         - imap
#         - intl
#         - json
#         - mcrypt
#         - memcache
#         - mongo
#         - mysql
#         - pgsql
#         - sqlite
#         - xmlrpc
#         - xsl

# nginx:
#     root: / # relative to vagrant home

# mysql:
#     version: 5.5 # or 5.6
#     admin: false

# redis:
#     admin: false

# mongodb:
#     admin: false

# nodejs:
#    packages:
#         - bower
#         - grunt-cli
#         - gulp
#         - jslint
#         - phantomjs

# sass:

# beanstalkd:
#     admin: false
